<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160107095600 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE mstruebing_tweetly_domain_model_user (persistence_object_identifier VARCHAR(40) NOT NULL, username VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE mstruebing_tweetly_domain_model_tweet (persistence_object_identifier VARCHAR(40) NOT NULL, author VARCHAR(40) DEFAULT NULL, content VARCHAR(255) NOT NULL, date DATETIME NOT NULL, INDEX IDX_F48C674EBDAFD8C8 (author), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE mstruebing_tweetly_domain_model_tweet ADD CONSTRAINT FK_F48C674EBDAFD8C8 FOREIGN KEY (author) REFERENCES mstruebing_tweetly_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE typo3_flow_security_account CHANGE failedauthenticationcount failedauthenticationcount INT DEFAULT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE mstruebing_tweetly_domain_model_tweet DROP FOREIGN KEY FK_F48C674EBDAFD8C8");
		$this->addSql("DROP TABLE mstruebing_tweetly_domain_model_user");
		$this->addSql("DROP TABLE mstruebing_tweetly_domain_model_tweet");
		$this->addSql("ALTER TABLE typo3_flow_security_account CHANGE failedauthenticationcount failedauthenticationcount INT DEFAULT 0");
	}
}