-
  name: 'Index Route'
  uriPattern: ''
  defaults:
    '@package': 'MStruebing.Tweetly'
    '@controller': 'User'
    '@action': 'index'

-
  name: 'Login Route'
  uriPattern: 'login'
  defaults:
    '@package': 'MStruebing.Tweetly'
    '@controller': 'Login'
    '@action': 'index'

-
  name: 'authenticate Route'
  uriPattern: 'authenticate'
  defaults:
    '@package': MStruebing.Tweetly
    '@controller': 'Login'
    '@action': 'authenticate'

-
  name: 'new User Route'
  uriPattern: 'register'
  defaults:
    '@package': MStruebing.Tweetly
    '@controller': 'User'
    '@action': 'new'

-
  name: 'create User Route'
  uriPattern: 'register/create'
  defaults:
    '@package': MStruebing.Tweetly
    '@controller': 'User'
    '@action': 'create'
